version: "3.7"

services: 
  bnext-contact-book-api:
    build: 
      dockerfile: docker/local/dockerfile
    ports: 
      - 9229:9229  
    volumes: 
      - ../../dist:/opt/bnext/contact-book-api/dist
      - ../../src:/opt/bnext/contact-book-api/src
      - ../../node_modules:/opt/bnext/contact-book-api/node_modules
    networks: 
      - bnext-contact-book-network-database
    environment: 
      DATABASE_HOST: bnext-contact-database 
      DATABASE_PORT: $DATABASE_PORT
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_COLLECTION: $DATABASE_COLLECTION
  bnext-contact-database:
    container_name: bnext-contact-database 
    build: 
      context: ../..
      dockerfile: docker/database/mysql/dockerfile
    ports: 
      - 3306:$DATABASE_PORT
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: $DATABASE_USER
      MYSQL_PASSWORD: $DATABASE_PASSWORD
      MYSQL_DATABASE: $DATABASE_COLLECTION
    networks:
      - bnext-contact-book-network-database
    
networks: 
  bnext-contact-book-network-database: 
    driver: bridge     